services:
  web:
    build:
      context: app
      target: builder
    volumes:
      - ./app:/var/www/html/
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"